### ISSUE TITLE
Quit when dead

### ISSUE THREAD

**Issue by hugosenari** [jiro4989/gameoflife#11]
**Describe the solution you'd like**
I think we should let our dead cells rest in peace, instead of keep stepping in their bodies.
I mean, it should stop (exit 0) when all cells are dead.

**Describe alternatives you've considered**
Also ends when command has same state in two consecutive steps

**Additional context**
In theory, it [isn't true that the state would never change](https://www.youtube.com/watch?v=AaZ_RSt0KP8) in these cases, but I don't think it would be a common, neither someone will await for it.

**Comment by jiro4989** [comment]
@hugosenari done

```bash
$ gameoflife ./examples/read_file/in/stop.txt
Press Ctrl-C to stop this program
Step count: 1
|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|
|0|0|0|0|0|0|1|1|0|0|0|1|1|0|0|0|0|0|1|1|0|0|0|1|1|0|0|
|0|1|1|0|0|1|0|0|1|0|0|1|0|1|0|0|0|1|0|1|0|0|1|0|0|1|0|
|0|1|1|0|0|0|1|1|0|0|0|0|1|0|0|0|0|1|1|0|0|0|1|0|0|1|0|
|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|1|1|0|0|
|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|

[INFO] Gameoflife has stopped because of cell states were same in 2 consecutive steps
[INFO] See you
```
