### ISSUE TITLE
Use example as bin instead of main

### ISSUE THREAD

**Issue by hugosenari** [jiro4989/gameoflife#5]
Maybe could be cool if nimble package add examples as bin

**Comment by jiro4989** [comment]
Added an example program (read\_file) to MainModule.

![gameoflife](https://user-images.githubusercontent.com/13825004/158581629-79ed4f75-f212-4225-8dbf-4f50e8e78c2d.gif)

**Comment by hugosenari** [comment]
I was thinking you would add examples/x/x.nim to `bin` in nimble package, but your solution was even better :)
Now I can run it with maze more easily in my NixOS
```sh
g/gameoflife/result/bin/gameoflife <(m/maze/result/bin/maze -w:0 -r:1 -W:10 -H:10)
```
Thank you.
